name: Build and Upload Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install and switch to GCC 10
        run: |
          sudo apt update
          sudo apt install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10
          sudo update-alternatives --set gcc /usr/bin/gcc-10
        shell: bash

      - name: Verify GCC version
        run: gcc --version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          release: R2022a

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests pyyaml
      
      - name: Prepare packages
        env:
          BUILD_ARCHITECTURE: linux_x86_64
        run: |
          python scripts/prepare_packages.py
      
      - name: Compile packages
        env:
          BUILD_ARCHITECTURE: linux_x86_64
        uses: matlab-actions/run-command@v2
        with:
          command: "cd scripts; compile_packages"
      
      - name: Bundle packages
        env:
          BUILD_ARCHITECTURE: linux_x86_64
        run: |
          python scripts/bundle_packages.py
      
      - name: Upload packages
        env:
          BUILD_ARCHITECTURE: linux_x86_64
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          python scripts/upload_packages.py
  
  build-macos-intel:
    runs-on: macos-15-intel

    steps:
      - name: Make alias for gfortran
        run: |
          gfortran-15 --version
          alias gfortran=gfortran-15
          gfortran --version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests pyyaml
      
      - name: Prepare packages
        env:
          BUILD_ARCHITECTURE: macos_x86_64
        run: |
          python scripts/prepare_packages.py
      
      - name: Compile packages
        env:
          BUILD_ARCHITECTURE: macos_x86_64
        uses: matlab-actions/run-command@v2
        with:
          command: "cd scripts; compile_packages"
      
      - name: Bundle packages
        env:
          BUILD_ARCHITECTURE: macos_x86_64
        run: |
          python scripts/bundle_packages.py
      
      - name: Upload packages
        env:
          BUILD_ARCHITECTURE: macos_x86_64
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          python scripts/upload_packages.py

  build-macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
    
      - name: Make alias for gfortran
        run: |
          gfortran-15 --version
          alias gfortran=gfortran-15
          gfortran --version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests pyyaml
      
      - name: Prepare packages
        env:
          BUILD_ARCHITECTURE: macos_arm64
        run: |
          python scripts/prepare_packages.py
      
      - name: Compile packages
        env:
          BUILD_ARCHITECTURE: macos_arm64
        uses: matlab-actions/run-command@v2
        with:
          command: "cd scripts; compile_packages"
      
      - name: Bundle packages
        env:
          BUILD_ARCHITECTURE: macos_arm64
        run: |
          python scripts/bundle_packages.py
      
      - name: Upload packages
        env:
          BUILD_ARCHITECTURE: macos_arm64
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          python scripts/upload_packages.py

  assemble-index:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-macos-intel]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests pyyaml
      
      - name: Assemble package index
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          python scripts/assemble_index.py
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: assemble-index
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
